[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
flake = "5cYJsEQDUHGQuZ3SuSRjAN14g23iXtWboqoFJ6fJHtYM"

[registry]
url = "https://api.localnet.solana.com"

[provider]
cluster = "localnet"
wallet = "./id2.json"
#wallet = "~/.config/solana/id.json"
[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
compute_unit_limit = 1000000