[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
flake = "8zYMYyqVyLtY8HZQjcCcvfAHzstZRRbkRyvLc9fmvYHG"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
