[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
flake = "8zYMYyqVyLtY8HZQjcCcvfAHzstZRRbkRyvLc9fmvYHG"

[registry]
url = "https://api.localnet.solana.com"

[provider]
cluster = "localnet"
#wallet = "./id.json"
wallet = "~/.config/solana/id.json"
[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
compute_unit_limit = 1000000